Yahzee: color.c File Reference
color.c File Reference
#include <stdio.h>
Functions
void red ()
void yellow ()
void green ()
void resetColor ()
Function Documentation
green()
void green ()
Definition at line 9 of file color.c.
Referenced by displayTabScore().
              {
   printf("\033[1;32m");
 }
red()
void red ()
Definition at line 2 of file color.c.
Referenced by displayTabScore().
             {
   printf("\033[1;31m");
 }
resetColor()
void resetColor ()
Definition at line 13 of file color.c.
Referenced by displayTabScore().
                    {
   printf("\033[0m");
 }
yellow()
void yellow ()
Definition at line 6 of file color.c.
               {
   printf("\033[1;33m");
 }