Yahzee: mecanismeJeu.h File Reference
mecanismeJeu.h File Reference
#include <stdio.h>
#include <time.h>
#include <unistd.h>
#include "score.h"
Data Structures
struct Player
Macros
#define MAX_COMBINATOIRE 20
Typedefs
typedef struct Player Player
Functions
int tirage (int max)
donne la valeur de dée
void rollDices (Player *p)
la coup de jeu
void refreshDices (Player *p)
initialise les dées
void displayDices (Player *p)
affichage des dées.
void askDices (Player *p)
relance les dées
void completeTurn (Player *p)
lance une partie de jeu.
void freePlayer (Player *p)
libére la memoire.
Macro Definition Documentation
MAX_COMBINATOIRE
#define MAX_COMBINATOIRE 20
Definition at line 5 of file mecanismeJeu.h.
Referenced by main().
Typedef Documentation
Player
typedef struct Player Player
Definition at line 8 of file mecanismeJeu.h.
Function Documentation
askDices()
void askDices (Player * p)
relance les dées
demande au joueur s'il veurt relancer le dée.
Parameters
p le joueur.
Definition at line 76 of file mecanismeJeu.c.
References boucle_de_saisie(), Player::dices, Player::dicesAllowed, and displayDices().
Referenced by completeTurn().
{
   for (int i = 0; i <7; ++i)
   {displayDices(p);
     if(p-> dicesAllowed[i]==1){
       printf("voulez vous relancer le de %d ?\n",p->dices[i] );
       boucle_de_saisie(&(p->dicesAllowed[i]),0,1);
     }
   }
 }
completeTurn()
void completeTurn (Player * p)
lance une partie de jeu.
fait une partie de jeu .
Parameters
p le joueur.
Definition at line 94 of file mecanismeJeu.c.
References askDices(), boucle_de_saisie(), Player::dices, displayDices(), displayScore(), displayTabScore(), Player::nbrRollRemain, refreshDices(), rollDices(), saisitScore(), Player::tabScore, and Player::tabScoreFinal.
Referenced by main().
{
   refreshDices(p) ;
   int answer=1;
   do{
     printf("Lance de dees :\n") ;
     rollDices(p) ;
     displayDices(p) ;
     printf("Essaies restante : %d\n", p->nbrRollRemain) ;
     printf("Score temporaire :\n");
     displayScore(p->tabScore, p->dices,p->tabScoreFinal);
     if(p->nbrRollRemain>0){
         printf("Voulez vous relancer des dees ? ") ;
         boucle_de_saisie(&answer,0,1) ;
         if(!answer){
             p->nbrRollRemain =0;
         }
         else{
             askDices(p);
         }
     }
   }while(p->nbrRollRemain >= 0);
     saisitScore(p->tabScore,p->tabScoreFinal);
     for (int i = 0; i < 20; ++i)
     {
         printf("%d\n", p->tabScoreFinal[i] );
     }
   displayTabScore(p->tabScore,p->tabScoreFinal);//affiche son score final
 }
displayDices()
void displayDices (Player * p)
affichage des dées.
afficher tout les dées.
Parameters
p le joueur.
Definition at line 62 of file mecanismeJeu.c.
References Player::dices.
Referenced by askDices(), and completeTurn().
{
   for(int i = 0 ; i < 7 ; ++i){
     printf("%d ", p->dices[i]) ;
   }
   printf("\n") ;
 }
freePlayer()
void freePlayer (Player * p)
libére la memoire.
libere la memoire allouer pour les joueurs .
Parameters
p le joueur.
Definition at line 136 of file mecanismeJeu.c.
References Player::dices, Player::dicesAllowed, Player::tabScore, and Player::tabScoreFinal.
Referenced by main().
{
         free(p->dices);
         free(p->dicesAllowed);
         free(p->tabScore);
         free(p->tabScoreFinal);
 }
refreshDices()
void refreshDices (Player * p)
initialise les dées
initialize toute les dées a 0.
Parameters
p le joueur.
Definition at line 48 of file mecanismeJeu.c.
References Player::dices, and Player::dicesAllowed.
Referenced by completeTurn().
{
   for(int i = 0 ; i < 7 ; ++i){
     p->dices[i] = 0 ;
     p->dicesAllowed[i]=1;
   }
 }
rollDices()
void rollDices (Player * p)
la coup de jeu
fait le coup de 7 deés
Parameters
p le joueur
Definition at line 32 of file mecanismeJeu.c.
References Player::dices, Player::dicesAllowed, Player::nbrRollRemain, and tirage().
Referenced by completeTurn().
{
   srand((unsigned)time(NULL));//set Seed pour le tirage
   for(int i = 0 ; i < 7; ++i){
     if (p->dicesAllowed[i]){
       p->dices[i] = tirage(8) ;
       //printf(">>>de %d tire%d\n",i,p->dices[i] );
     }
   }
   p->nbrRollRemain-=1;
 }
tirage()
int tirage (int max)
donne la valeur de dée
Parameters
max le maximum
Returns
Un int représentant la valeur de dée.
Definition at line 19 of file mecanismeJeu.c.
Referenced by rollDices().
                    {
     /*tire au sort un nombre compris entre 0 inclus max;
     srand((unsigned)time(NULL));*/
     rand();
     return (double)(rand()/(double)(RAND_MAX) * (max))+1;
 }