My Project: mecanismeJeu.c File Reference
mecanismeJeu.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "mecanismeJeu.h"
#include "score.h"
Functions
int tirage (int max)
void rollDices (Player *p)
void refreshDices (Player *p)
int boucle_de_saisie (int a, int b)
void displayDices (Player *p)
void askDices (Player *p)
void completeTurn (Player *p)
void freePlayer (Player *p)
void initPlayer (Player *p)
Function Documentation
askDices()
void askDices (Player * p)
Definition at line 51 of file mecanismeJeu.c.
References boucle_de_saisie().
Referenced by completeTurn().
{
   for (int i = 0; i <8; ++i)
   {
     if(p-> dicesAllowed[i]==1){
       printf("voulez vous relancer le de %d ?\n",i+1 );
       p-> dicesAllowed[i]= boucle_de_saisie(0,1);
     }
   }
 }
boucle_de_saisie()
int boucle_de_saisie (int a, int b)
Definition at line 32 of file mecanismeJeu.c.
Referenced by askDices(), and completeTurn().
{
     //retourne l'entier i ssi il est compris dans intervalle [a,b]
     int i;
     do{
         fflush(stdin);
         printf("merci de saisir un nombre compris entre %d et %d\n", a, b);
         scanf("%d",&i);
     }while( i <a || i>b ||sizeof(i) != sizeof(int) );
     return i;
 }
completeTurn()
void completeTurn (Player * p)
Definition at line 63 of file mecanismeJeu.c.
Referenced by main().
{
   int v = 1 ;
   refreshDices(p) ;
   rollDices(p) ;
   p->nbrRollRemain -= 1 ;
   while(p->nbrRollRemain != 0){
     printf("Lancé de dée :\n") ;
     displayDices(p) ;
     printf("Voulez vous relancer des dées ? ") ;
     v = boucle_de_saisie(0,1) ;
     if(v == 0) { // cas fin de lance
       p->nbrRollRemain = 0 ;
       displayScore(p->tabScore,p->dices);
       }
     else{ //cas relance de
       if(p->nbrRollRemain !=6)printf("lequelles one ? ") ;
       askDices(p);
       p->nbrRollRemain -= 1 ;
       rollDices(p) ;
       printf("Vous avez relancé des dées :\n") ;
       displayScore(p->tabScore,p->dices);
       printf("Essaies restante : %d\n", p->nbrRollRemain) ;
     }
   }
   printf("Tour du prochain joueur\n") ;
 }
displayDices()
void displayDices (Player * p)
Definition at line 43 of file mecanismeJeu.c.
References Player::dices.
Referenced by completeTurn().
{
   for(int i = 0 ; i < 8 ; ++i){
     printf("%d ", p->dices[i]) ;
   }
   printf("\n") ;
 }
freePlayer()
void freePlayer (Player * p)
Definition at line 93 of file mecanismeJeu.c.
References Player::dices, Player::dicesAllowed, and Player::tabScore.
Referenced by main().
{
   free(p->dices);
   free(p->dicesAllowed);
   free(p->tabScore);
 }
initPlayer()
void initPlayer (Player * p)
Definition at line 98 of file mecanismeJeu.c.
References Player::dices, Player::dicesAllowed, Player::nbrRollRemain, Player::score, and Player::tabScore.
Referenced by main().
{
   //askName();
   p->dices = malloc(sizeof(int)*8);
   p->dicesAllowed = malloc(sizeof(int)*8);
   p->nbrRollRemain = 6 ;
   p->score = 0;
   p->tabScore = malloc(sizeof(int)*6);
   for (int i = 0; i < 6; ++i)
   {
     p->tabScore[i]= 0;
   }
 }
refreshDices()
void refreshDices (Player * p)
Definition at line 23 of file mecanismeJeu.c.
References Player::dices, and Player::dicesAllowed.
Referenced by completeTurn().
{
   for(int i = 0 ; i < 8 ; ++i){
     p->dices[i] = 0 ;
     p->dicesAllowed[i]=1;
   }
 }
rollDices()
void rollDices (Player * p)
Definition at line 13 of file mecanismeJeu.c.
References Player::dices, Player::dicesAllowed, and tirage().
Referenced by completeTurn().
{
   srand((unsigned)time(NULL));//set Seed pour le tirage
   for(int i = 0 ; i < 8; ++i){
     if (p->dicesAllowed[i]){
       p->dices[i] = tirage(8) ;
       //printf(">>>de %d tire%d\n",i,p->dices[i] );
     }
   }
 }
tirage()
int tirage (int max)
Definition at line 6 of file mecanismeJeu.c.
Referenced by rollDices().
                    {
     /*tire au sort un nombre compris entre 0 inclus max;
     srand((unsigned)time(NULL));*/
     rand();
     return (double)(rand()/(double)(RAND_MAX) * (max))+1;
 }