My Project: proto.c File Reference
proto.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <stdarg.h>
#include "mecanismeJeu.h"
Functions
int tirage (int max)
void rollDices (Player *p)
void beginTurn (Player *p)
int boucle_de_saisie (int a, int b)
void displayDices (Player *p)
void completeTurn (Player *p)
int main (void)
Function Documentation
beginTurn()
void beginTurn (Player * p)
Definition at line 41 of file proto.c.
References Player::dices, Player::dicesAllowed, and Player::nbrRollRemain.
Referenced by completeTurn().
{
   for(int i = 0 ; i < 6 ; ++i){
     p->dices[i] = 0 ;
     p->dicesAllowed[i]=1;
   }
   p->nbrRollRemain = 6 ;
 }
boucle_de_saisie()
int boucle_de_saisie (int a, int b)
Definition at line 51 of file proto.c.
Referenced by completeTurn().
{
     //retourne l'entier i ssi il est compris dans intervalle [a,b]
     int i;
     do{
         fflush(stdin);
         //necessaire pour eviter un bug de boucle infinie si utilisateur saisie un type non int comme une charactere par exemple
         //meme si un char est un int...(scanf)
         printf("merci de saisir un nombre compris entre %d et %d\n", a, b);
         scanf("%d",&i);
     }while( i <a || i>b ||sizeof(i) != sizeof(int) );
     return i;
 }
completeTurn()
void completeTurn (Player * p)
Definition at line 73 of file proto.c.
References askDices(), beginTurn(), boucle_de_saisie(), Player::dices, displayDices(), displayScore(), Player::nbrRollRemain, refreshDices(), rollDices(), and Player::tabScore.
Referenced by main().
{
   int v = 1 ;
   int i = 0 ;
   beginTurn(p) ;
   while(p->nbrRollRemain != 0){
     printf("Actual outcome :\n") ;
     displayDices(p) ;
     printf("Retoss some dice ? ") ;
     //scanf("%d", &v) ;
     v = boucle_de_saisie(0,1) ;
     if(v == 0) { p->nbrRollRemain = 0 ; } //TODO appeler l'affichage de la grille
     else{
       int roll = 1 ;
       while(roll == 1 && p->nbrRollRemain != 0){
     printf("Which one ? ") ;
     scanf("%d", &p->wannaRoll[i]) ;
     ++i ;
     printf("Select one other dice ? ") ;
     scanf("%d", &roll) ;
       }
       p->nbrRollRemain -= 1 ;
       rollDices(p) ;
       printf("You've toss %d dice(s) again :\nOUTCOME\n", i) ;
       displayDices(p) ;
       printf("Remaining try : %d\n", p->nbrRollRemain) ;
     }
   }
   printf("Next turn\n") ;
 }
displayDices()
void displayDices (Player * p)
Definition at line 64 of file proto.c.
References Player::dices.
Referenced by completeTurn().
{
   for(int i = 0 ; i < 6 ; ++i){
     printf("%d ", p->dices[i]) ;
     printf("... ");
     sleep(1);
   }
   printf("\n") ;
 }
main()
int main (void)
Definition at line 104 of file proto.c.
References completeTurn(), and Player::dices.
                {
   printf("NOTE : répondre par 1 ou 0 aux questions et pour selection des dès leurs indexs [1-7]\n\n");
   Player *p ;
   Player firstPlayer ;
   p = &firstPlayer ;
   p->dices = malloc(sizeof(int) * 7) ;
   if(p->dices == NULL) printf("p == Null !\n") ;
   completeTurn(p) ;
   return(0) ;
 }
rollDices()
void rollDices (Player * p)
Definition at line 31 of file proto.c.
References Player::dices, and tirage().
Referenced by completeTurn().
{
   srand((unsigned)time(NULL));//set Seed pour le tirage
   for(int i = 0 ; i < 8; ++i){
     // int sub = va_arg(va, int) ;
     if (dicesAllowed[i]){
       p->dices[p->wannaRoll[i]] = tirage(8) ;
     }
   }
 }
tirage()
int tirage (int max)
Definition at line 24 of file proto.c.
Referenced by rollDices().
                    {
     /*tire au sort un nombre compris entre 0 inclus max;
     srand((unsigned)time(NULL));*/
     rand();
     return (double)(rand()/(double)(RAND_MAX) * (max))+1;
 }