Yahzee: score.h File Reference
score.h File Reference
#include <stdio.h>
#include <stdlib.h>
Functions
int testYahtzee (int *tab)
Verifie si la figure Yahtzee est présente.
int testPetiteSuite (int *tab)
Verifie si la figure PetiteSuite est présente.
int testGrandeSuite (int *tab)
Verifie si la figure GrandeSuite est présente.
int testBrelan (int *tab)
Verifie si la figure Brelan est présente.
int testCarre (int *tab)
int testFullv1 (int *tab)
Verifie si la figure Full type1 est présente (5des identique + 2des identiques)
int testFullv2 (int *tab)
Verifie si la figure Full type2 est présente (3des identique + 4des identiques)
void testCombinatoire (int *tab_score, int *tab_dee)
Appel a tout les fonctions de verification de figure.
void displayScore (int *tab_score, int *tab_dee, int *tabFinal)
Affiche les scores.
void compareScore (int a, int b)
Fonction qui décide qui l'emporte.
int sommeScore (int *tab)
int saisitScore (int *tab, int *tabFinal)
void displayTabScore (int *tab_score, int *tabFinal)
int boucle_de_saisie (int *p, int low, int high)
Function Documentation
boucle_de_saisie()
int boucle_de_saisie (int * p, int low, int high)
Definition at line 489 of file score.c.
Referenced by askDices(), completeTurn(), and saisitScore().
{
     while(1) {
         const int BUFSIZE = 256;
         char buf[BUFSIZE];
         printf("merci de saisir un nombre compris entre %d et %d\n", low, high);
         if ( fgets( buf, BUFSIZE, stdin ) == NULL ) {
             return 0;      // almost certainly EOF
         }
         if ( sscanf( buf, "%d", p ) != 1 ) {
             printf( "Merci de saisir un entier\n" );
         }
         else if ( * p < low || * p > high )  {
             printf("valeur saisie hors borne\n");
         }
         else {
             break;
         }
     }
     return 1;
 }
compareScore()
void compareScore (int a, int b)
Fonction qui décide qui l'emporte.
Compare le score des deux joueurs et affiche le gagnant ou match nul
Parameters
a score du joueur 1
b score du joueur 2
Definition at line 369 of file score.c.
Referenced by main().
{
     if(a > b){
         printf("Bravo! le joueur 1 remporte la partie\n");
     }
     else if (b > a){
         printf("Bravo! le joueur 2 remporte la partie\n");
     }
     else{
         printf("Match nul\n");
     }
 }
displayScore()
void displayScore (int * tab_score, int * tab_dee, int * tabFinal)
Affiche les scores.
Appel la fonction TestCombinatoire qui s'occupe de remplir le tableau des score, puis affiche les scores
Parameters
*tab_score tableau contenant les scores
*tab_dee tableau contenant les des
Definition at line 351 of file score.c.
References displayTabScore(), and testCombinatoire().
Referenced by completeTurn().
{
     testCombinatoire(tab_score,tab_dee);
     displayTabScore(tab_score, tabFinal);
 }
displayTabScore()
void displayTabScore (int * tab_score, int * tabFinal)
Definition at line 393 of file score.c.
References green(), red(), and resetColor().
Referenced by completeTurn(), and displayScore().
{
     printf("========================================================\n" );
     (tabFinal[0] == -1)? green(): red();
     printf("%-4s %-12s: %d\n"," 1 >>", "AS", tab_score[0]);
     (tabFinal[1] == -1)? green(): red();
     printf("%-4s %-12s: %d\n"," 2 >>", "DEUX", tab_score[1]);
     (tabFinal[2] == -1)? green(): red();
     printf("%-4s %-12s: %d\n"," 3 >>", "TROIS", tab_score[2]);
     (tabFinal[3] == -1)? green(): red();
     printf("%-4s %-12s: %d\n"," 4 >>", "QUATRE", tab_score[3]);
     (tabFinal[4] == -1)? green(): red();
     printf("%-4s %-12s: %d\n"," 5 >>", "CINQ", tab_score[4]);
     (tabFinal[5] == -1)? green(): red();
     printf("%-4s %-12s: %d\n"," 6 >>", "SIX", tab_score[5]);
     (tabFinal[6] == -1)? green(): red();
     printf("%-4s %-12s: %d\n"," 7 >>", "SEPT", tab_score[6]);
     (tabFinal[7] == -1)? green(): red();
     printf("%-4s %-12s: %d\n"," 8 >>", "HUIT", tab_score[7]);
     (tabFinal[8] == -1)? green(): red();
     printf("%-4s %-12s: %d\n"," 9 >>", "BRELAN", tab_score[8]);
     (tabFinal[9] == -1)? green(): red();
     printf("%-4s %-12s: %d\n","10 >>", "SUITE(1-6)", tab_score[9]);
     (tabFinal[10] == -1)? green(): red();
     printf("%-4s %-12s: %d\n","11 >>", "SUITE(2-7)", tab_score[10]);
     (tabFinal[11] == -1)? green(): red();
     printf("%-4s %-12s: %d\n","12 >>", "CARRE", tab_score[11]);
     (tabFinal[12] == -1)? green(): red();
     printf("%-4s %-12s: %d\n","13 >>", "FULL(2+5)", tab_score[12]);
     (tabFinal[13] == -1)? green(): red();
     printf("%-4s %-12s: %d\n","14 >>", "FULL(3+4)", tab_score[13]);
     (tabFinal[14] == -1)? green(): red();
     printf("%-4s %-12s: %d\n","15 >>", "YAHTZEE", tab_score[14]);
     resetColor();
     printf("========================================================\n" );
 }
saisitScore()
int saisitScore (int * tab, int * tabFinal)
Definition at line 432 of file score.c.
References boucle_de_saisie().
Referenced by completeTurn().
{
     int answer=0;
     while(1){
         printf("Saisissez le numero de la case que vous voulez remplir  \n");
         boucle_de_saisie(&answer,1,15);
         --answer;
         if(tabFinal[answer] >= 0){
             printf("La case est deja remplit, merci de choisir une autre\n");
         }
         else{
             tabFinal[answer] = tab[answer];
             return 1;
         }
     }
 }
sommeScore()
int sommeScore (int * tab)
Definition at line 382 of file score.c.
Referenced by testBrelan(), and testCarre().
{
     int somme = 0;
     for (int i = 0; i < 7; ++i)
     {
         somme += tab[i];
     }
     return somme;
 }
testBrelan()
int testBrelan (int * tab)
Verifie si la figure Brelan est présente.
On parcours le tableau contenant les des, puis a chaque fois que des des réapparaisent, on fais +1 dans le tableau d'occurence. S'il y a une occurence de 3 dans le tableau d'occurence ET qu'il n'y a pas d'occurence de 4, alors on a un Brelan .
Parameters
*tab tableau content les des.
*tab_score tableau dans lequel on insere le score.
Definition at line 146 of file score.c.
References sommeScore().
Referenced by testCombinatoire().
{
   int tab_occurence[8]={0,0,0,0,0,0,0,0};
   int find = 0,i;
     for (i = 0; i < 7; ++i)
     {
         ++tab_occurence[tab[i]-1];
     }
     for (i = 0; i < 8; ++i)
     {
         if (tab_occurence[i] == 3)
         {
             printf("Il y a un Brelan de %d \n",i+1);
             ++find;
         }
     }
     if(find)
         return sommeScore(tab);
     return 0;
 }
testCarre()
int testCarre (int * tab)
Definition at line 460 of file score.c.
References sommeScore().
Referenced by testCombinatoire().
{
     int i;
     int tab_occurence[8]={0,0,0,0,0,0,0,0};
     for (i = 0; i < 7; ++i)
     {
         ++tab_occurence[tab[i]-1];
     }
     for (i = 0; i < 8; ++i)
     {
         if (tab_occurence[i] == 4)
         {
             printf("Il y a un Carre de %d \n",i+1);
             return sommeScore(tab);
         }
     }
     return 0;
 }
testCombinatoire()
void testCombinatoire (int * tab_score, int * tab_dee)
Appel a tout les fonctions de verification de figure.
Appel tout les fonctions de verification de figure et remplissage tableau de score
Parameters
*tab_score tableau contenant les scores
*tab_dee tableau contenant les des
Definition at line 322 of file score.c.
References testBrelan(), testCarre(), testFullv1(), testFullv2(), testGrandeSuite(), testPetiteSuite(), and testYahtzee().
Referenced by displayScore().
{
     /*test et remplit le tableau des score*/
     int i;
     for (i = 0; i < 7; ++i)
     {
         tab_score[tab_dee[i]-1] += tab_dee[i] ;
     }
     tab_score[8] = testBrelan(tab_dee);
     tab_score[9] = testPetiteSuite(tab_dee);
     tab_score[10] = testGrandeSuite(tab_dee);
     tab_score[11] = testCarre(tab_dee);
     tab_score[12] = testFullv1(tab_dee);
     tab_score[13] = testFullv2(tab_dee);
     tab_score[14] = testYahtzee(tab_dee);
 }
testFullv1()
int testFullv1 (int * tab)
Verifie si la figure Full type1 est présente (5des identique + 2des identiques)
On parcours le tableau contenant les des, puis a chaque fois que des des réapparaisent, on fais +1 dans le tableau d'occurence. S'il y a une occurence de 5 dans le tableau d'occurence ET qu'il y a une occurence de 2, alors on a un Full type1 .
Parameters
*tab tableau content les des.
*tab_score tableau dans lequel on insere le score.
Definition at line 177 of file score.c.
Referenced by testCombinatoire().
{
   int tab_occurence[8]={0,0,0,0,0,0,0,0};
   int i,j;
   int full1,full2;
   for(i=0;i<7;i++) {
     if(tab[i] == 1){
       tab_occurence[0]+=1;
     }
     else if(tab[i] == 2)
       {
     tab_occurence[1]+=1;
       }
     else if(tab[i] == 3)
       {
     tab_occurence[2]+=1;
       }
     else if(tab[i] == 4)
       {
     tab_occurence[3]+=1;
       }
     else if(tab[i] == 5)
       {
     tab_occurence[4]+=1;
       }
     else if(tab[i] == 6)
       {
     tab_occurence[5]+=1;
       }
     else if(tab[i] == 7)
       {
     tab_occurence[6]+=1;
       }
     else if(tab[i] == 8)
       {
     tab_occurence[7]+=1;
       }
   }
     for(i=0;i<8;i++)
       {
     if(tab_occurence[i]==5)
       {
         full1=i+1;
         for(j=0;j<8;j++)
           {
         if(tab_occurence[j]==2)
           {
             full2=j+1;
             printf("Il y a un Full de %d et %d\n",full1,full2);
             return 25;
           }
           }
       }
       }
     return 0;
 }
testFullv2()
int testFullv2 (int * tab)
Verifie si la figure Full type2 est présente (3des identique + 4des identiques)
On parcours le tableau contenant les des, puis a chaque fois que des des réapparaisent, on fais +1 dans le tableau d'occurence. S'il y a une occurence de 3 dans le tableau d'occurence ET qu'il y a une occurence de 4, alors on a un Full type2 .
Parameters
*tab tableau content les des.
*tab_score tableau dans lequel on insere le score.
Definition at line 250 of file score.c.
Referenced by testCombinatoire().
{
   int tab_occurence[8]={0,0,0,0,0,0,0,0};
   int i,j;
   int full1,full2;
   for(i=0;i<7;i++) {
     if(tab[i] == 1){
       tab_occurence[0]+=1;
     }
     else if(tab[i] == 2)
       {
     tab_occurence[1]+=1;
       }
     else if(tab[i] == 3)
       {
     tab_occurence[2]+=1;
       }
     else if(tab[i] == 4)
       {
     tab_occurence[3]+=1;
       }
     else if(tab[i] == 5)
       {
     tab_occurence[4]+=1;
       }
     else if(tab[i] == 6)
       {
     tab_occurence[5]+=1;
       }
     else if(tab[i] == 7)
       {
     tab_occurence[6]+=1;
       }
     else if(tab[i] == 8)
       {
     tab_occurence[7]+=1;
       }
   }
     for(i=0;i<8;i++)
       {
     if(tab_occurence[i]==3)
       {
         full1=i+1;
         for(j=0;j<8;j++)
           {
         if(tab_occurence[j]==4)
           {
             full2=j+1;
             printf("Il y a un Full de %d et %d\n",full1,full2);
              return 25;
           }
           }
       }
       }
     return 0;
 }
testGrandeSuite()
int testGrandeSuite (int * tab)
Verifie si la figure GrandeSuite est présente.
S'il y a une des qui vaut 2, on regard s'il y a une des qui vaut 3, ainsi de suite jusqu'a 7, si 7 est présent, alors il y a GrandeSuite
Parameters
*tab tableau content les des.
*tab_score tableau dans lequel on insere le score.
Definition at line 87 of file score.c.
Referenced by testCombinatoire().
{
     int i;
   // verif grande suite
    for(i=0;i<7;i++){
         if(tab[i] == 2)
       {
         for(i=0;i<7;i++){
           if(tab[i] == 3)
          {
            for(i=0;i<7;i++){
              if(tab[i] == 4)
                 {
               for(i=0;i<7;i++){
                 if(tab[i] == 5)
                    {
                  for(i=0;i<7;i++){
                    if(tab[i] == 6)
                       {
                     for(i=0;i<7;i++){
                       if(tab[i] == 7)
{
                            for(i=0;i<7;i++){
                          if(tab[i] == 8)
{
                               printf("Il y a une GrandeSuite\n");
                              return 40;
                            }
                            }
                          }
                     }
                       }
                  }
                    }
               }
             }
            }
          }
         }
       }
    }
    return 0;
 }
testPetiteSuite()
int testPetiteSuite (int * tab)
Verifie si la figure PetiteSuite est présente.
S'il y a une des qui vaut 1, on regard s'il y a une des qui vaut 2, ainsi de suite jusqu'a 7,si 7 est présent, alors on a une PetiteSuite
Parameters
*tab tableau content les des.
*tab_score tableau dans lequel on insere le score.
Definition at line 35 of file score.c.
Referenced by testCombinatoire().
{
     int i;
     // verif petite suite
   for(i=0;i<7;i++){
         if(tab[i] == 1)
       {
         for(i=0;i<7;i++){
           if(tab[i] == 2)
          {
            for(i=0;i<7;i++){
              if(tab[i] == 3)
                 {
               for(i=0;i<7;i++){
                 if(tab[i] == 4)
                    {
                  for(i=0;i<7;i++){
                    if(tab[i] == 5)
                       {
                     for(i=0;i<7;i++){
                       if(tab[i] == 6)
{
                            for(i=0;i<7;i++){
                          if(tab[i] == 7)
{
                              printf("Il y a une PetiteSuite\n");
                              return 30;
                            }
                            }
                          }
                     }
                       }
                  }
                    }
               }
             }
            }
          }
         }
       }
   }
   return 0;
   }
testYahtzee()
int testYahtzee (int * tab)
Verifie si la figure Yahtzee est présente.
Si la premiere des est équivalente a la suivante,on verifie si la suivante est équivalente à la prochaine de celle ci, ainsi de suite
Parameters
*tab tableau content les des.
*tab_score tableau dans lequel on insere le score.
Definition at line 13 of file score.c.
Referenced by testCombinatoire().
{
   // verif Yahtzee
   if(tab[0] == tab[1]
       &&tab[1] == tab[2]
       &&tab[2] == tab[3]
       &&tab[3] == tab[4]
       &&tab[4] == tab[5]
       &&tab[5] == tab[6]){
         printf("Il y a un Yahtzee de %d\n",tab[0]);
         return 50;
   }
   return 0;
 }