My Project: boucle.c File Reference
boucle.c File Reference
Correspond à là boucle principale du jeu.
#include "navalfight.h"
Functions
char * nomjoueur ()
Saisis les noms des joueurs.
void viderbuffer (void)
Fonction qui vide un buffer.
void findepartie (void)
Termine la partie.
void insert (char **grid, int ligne, int colonne)
Vérifie si les bateaux sont touchés.
int verifie (char **grid, int ligne, int colonne)
Vérifie les positions attaqué
int attaquer (char **grid)
Phase d'attaque.
void boucle (char **grid1, char **grid2)
Boucle principal du jeu.
Detailed Description
Correspond à là boucle principale du jeu.
Definition in file boucle.c.
Function Documentation
attaquer()
int attaquer (char ** grid)
Phase d'attaque.
Demande d'entré la ligne et colonne a laquelle le joueur souhaite attaquer. Puis appel la fonction verifie, qui s'occupe de voir s'il a touché un bateau.
Parameters
**grid Correspond à la grille.
Returns
Renvoie un entier qui vaut 0 si le joueur à touché un bateau ou raté, sinon 1.
Definition at line 125 of file boucle.c.
References verifie(), and viderbuffer().
Referenced by boucle().
boucle()
void boucle (char ** grid1, char ** grid2)
Boucle principal du jeu.
C'est la boucle principal du jeu, qui s'occupe d'appeler les différents fonctions .
Parameters
**grid1 Grille du joueur 1.
**grid2 Grille du joueur 2.
Definition at line 178 of file boucle.c.
References afficher(), attaquer(), and nomjoueur().
Referenced by main().
findepartie()
void findepartie (void)
Termine la partie.
Affiche Gagné et termine le programme . des coordonnées des points. (cf #Point)
Definition at line 51 of file boucle.c.
Referenced by insert().
insert()
void insert (char ** grid, int ligne, int colonne)
Vérifie si les bateaux sont touchés.
Si un bateau est touché remplace le '0' par '+' et affiche Gagné sinon Raté et affiche la position par '*'. Puis appel les fonction couler et put_couler pour vérifier si le bateau est coulé. Verifie ensuite si la partie est gagné .
Parameters
**grid La grille.
ligne Le nombre de ligne de la grille .
colonne Le nombre de colonne de la grille .
Definition at line 66 of file boucle.c.
References couler(), findepartie(), ft_detect_defaite(), and put_couler().
Referenced by verifie().
nomjoueur()
char* nomjoueur (void)
Saisis les noms des joueurs.
Crée un tableau via malloc pour y saisir le nom des joueurs .
Returns
Renvoie un char * , qui contient le nom du joueur .
Definition at line 17 of file boucle.c.
Referenced by boucle().
verifie()
int verifie (char ** grid, int ligne, int colonne)
Vérifie les positions attaqué
Vérifie si les positions attaqué avec la fonction insert, selon les cas 'Raté', 'Touché' ou déjà attaqué.
Parameters
**grid La grille.
ligne Le nombre de ligne de la grille .
colonne Le nombre de colonne de la grille .
Returns
Renvoie un entier, 0 si Touché un bateau ou Raté, sinon 1 .
Definition at line 99 of file boucle.c.
References insert().
Referenced by attaquer().
viderbuffer()
void viderbuffer (void)
Fonction qui vide un buffer.
Vide le buffer qui comporte la ligne et colonne joué pour les réutiliser au prochain tour de boucle.
Definition at line 36 of file boucle.c.
Referenced by attaquer().