My Project: create_grid.c File Reference
create_grid.c File Reference
Crée la grille de la bataille navale.
#include "navalfight.h"
Functions
int ft_test_born (int indice_col, int indice_line)
Vérifie si on reste bien dans la grille.
int ft_test_boat (char **grid, int indice_col, int indice_line)
Test s'il y a un bateau.
int ft_boat_1_2 (char **grid, int indice_col, int indice_line)
Place un bateau de dimension 2.
int ft_boat_1_3 (char **grid, int indice_col, int indice_line)
Place un bateau de dimension 3.
int ft_boat_1_4 (char **grid, int indice_col, int indice_line)
Place un bateau de dimension 4.
int ft_boat_1_5 (char **grid, int indice_col, int indice_line)
Place un bateau de dimension 5.
int ft_boat_1_6 (char **grid, int indice_col, int indice_line)
Place un bateau de dimension 6.
int ft_boat_2_2 (char **grid, int indice_col, int indice_line)
Place un bateau de dimension 4.
int ft_boat_2_4 (char **grid, int indice_col, int indice_line)
Place un bateau de dimension 8.
int ft_boat_1_4_1_3 (char **grid, int indice_col, int indice_line)
Place un bateau de dimension 6.
char ** ft_fill_grid (char **grid)
Fonction qui remplie la grille.
char ** cree_tableau (void)
Fonction qui crée la grille.
Detailed Description
Crée la grille de la bataille navale.
Definition in file create_grid.c.
Function Documentation
cree_tableau()
char** cree_tableau (void)
Fonction qui crée la grille.
Crée la grille, puis applique ft_fill_grid sur la grille pour la remplir .
Returns
Renvoie un char ** qui correspond à la grille.
Definition at line 773 of file create_grid.c.
References ft_fill_grid().
Referenced by main().
ft_boat_1_2()
int ft_boat_1_2 (char ** grid, int indice_col, int indice_line)
Place un bateau de dimension 2.
Vérifie s'il y a des bateaux aux alentours des coordonées passées, si non un bateau est placé en verifiant que l'on ne sors pas de la grille.
Parameters
**grid Grille de la bataille navale .
indice_col Premiere coordonée.
indice_line Seconde coordonée.
Returns
Renvoie un entier qui vaut 0 si le bateau a été placé, sinon 0.
Definition at line 56 of file create_grid.c.
References ft_test_boat(), and ft_test_born().
Referenced by ft_fill_grid().
ft_boat_1_3()
int ft_boat_1_3 (char ** grid, int indice_col, int indice_line)
Place un bateau de dimension 3.
Vérifie s'il y a des bateaux aux alentours des coordonées passées, si non un bateau est placé en verifiant que l'on ne sors pas de la grille.
Parameters
**grid Grille de la bataille navale .
indice_col Premiere coordonée.
indice_line Seconde coordonée.
Returns
Renvoie un entier qui vaut 0 si le bateau a été placé, sinon 0.
Definition at line 108 of file create_grid.c.
References ft_test_boat(), and ft_test_born().
Referenced by ft_fill_grid().
ft_boat_1_4()
int ft_boat_1_4 (char ** grid, int indice_col, int indice_line)
Place un bateau de dimension 4.
Vérifie s'il y a des bateaux aux alentours des coordonées passées, si non un bateau est placé en verifiant que l'on ne sors pas de la grille.
Parameters
**grid Grille de la bataille navale .
indice_col Premiere coordonée.
indice_line Seconde coordonée.
Returns
Renvoie un entier qui vaut 0 si le bateau a été placé, sinon 0.
Definition at line 167 of file create_grid.c.
References ft_test_boat(), and ft_test_born().
Referenced by ft_fill_grid().
ft_boat_1_4_1_3()
int ft_boat_1_4_1_3 (char ** grid, int indice_col, int indice_line)
Place un bateau de dimension 6.
Vérifie s'il y a des bateaux aux alentours des coordonées passées, si non un bateau est placé en verifiant que l'on ne sors pas de la grille.
Parameters
**grid Grille de la bataille navale .
indice_col Premiere coordonée.
indice_line Seconde coordonée.
Returns
Renvoie un entier qui vaut 0 si le bateau a été placé, sinon 0.
Definition at line 616 of file create_grid.c.
References ft_test_boat(), and ft_test_born().
Referenced by ft_fill_grid().
ft_boat_1_5()
int ft_boat_1_5 (char ** grid, int indice_col, int indice_line)
Place un bateau de dimension 5.
Vérifie s'il y a des bateaux aux alentours des coordonées passées, si non un bateau est placé en verifiant que l'on ne sors pas de la grille.
Parameters
**grid Grille de la bataille navale .
indice_col Premiere coordonée.
indice_line Seconde coordonée.
Returns
Renvoie un entier qui vaut 0 si le bateau a été placé, sinon 0.
Definition at line 245 of file create_grid.c.
References ft_test_boat(), and ft_test_born().
Referenced by ft_fill_grid().
ft_boat_1_6()
int ft_boat_1_6 (char ** grid, int indice_col, int indice_line)
Place un bateau de dimension 6.
Vérifie s'il y a des bateaux aux alentours des coordonées passées, si non un bateau est placé en verifiant que l'on ne sors pas de la grille.
Parameters
**grid Grille de la bataille navale .
indice_col Premiere coordonée.
indice_line Seconde coordonée.
Returns
Renvoie un entier qui vaut 0 si le bateau a été placé, sinon 0.
Definition at line 336 of file create_grid.c.
References ft_test_boat(), and ft_test_born().
Referenced by ft_fill_grid().
ft_boat_2_2()
int ft_boat_2_2 (char ** grid, int indice_col, int indice_line)
Place un bateau de dimension 4.
Vérifie s'il y a des bateaux aux alentours des coordonées passées, si non un bateau est placé en verifiant que l'on ne sors pas de la grille.
Parameters
**grid Grille de la bataille navale .
indice_col Premiere coordonée.
indice_line Seconde coordonée.
Returns
Renvoie un entier qui vaut 0 si le bateau a été placé, sinon 0.
Definition at line 439 of file create_grid.c.
References ft_test_boat(), and ft_test_born().
Referenced by ft_fill_grid().
ft_boat_2_4()
int ft_boat_2_4 (char ** grid, int indice_col, int indice_line)
Place un bateau de dimension 8.
Vérifie s'il y a des bateaux aux alentours des coordonées passées, si non un bateau est placé en verifiant que l'on ne sors pas de la grille.
Parameters
**grid Grille de la bataille navale .
indice_col Premiere coordonée.
indice_line Seconde coordonée.
Returns
Renvoie un entier qui vaut 0 si le bateau a été placé, sinon 0.
Definition at line 508 of file create_grid.c.
References ft_test_boat(), and ft_test_born().
Referenced by ft_fill_grid().
ft_fill_grid()
char** ft_fill_grid (char ** grid)
Fonction qui remplie la grille.
Choisis des coordonnées aléatoires et appel les fonctions qui place bateaux avec ces coordonées .
Parameters
**grid Grille de la bataille navale .
Returns
Renvoie un char ** qui correspond à la grille remplie .
Definition at line 714 of file create_grid.c.
References ft_boat_1_2(), ft_boat_1_3(), ft_boat_1_4(), ft_boat_1_4_1_3(), ft_boat_1_5(), ft_boat_1_6(), ft_boat_2_2(), and ft_boat_2_4().
Referenced by cree_tableau().
ft_test_boat()
int ft_test_boat (char ** grid, int indice_col, int indice_line)
Test s'il y a un bateau.
Verifie s'il y a bateau aux coordonées passé
Parameters
**grid La grille de la bataille navale.
indice_col Première coordonée.
indice_line Seconde coordonée.
Returns
Renvoie un entier 1 s'il y a un bateau, sinon 0.
Definition at line 40 of file create_grid.c.
Referenced by ft_boat_1_2(), ft_boat_1_3(), ft_boat_1_4(), ft_boat_1_4_1_3(), ft_boat_1_5(), ft_boat_1_6(), ft_boat_2_2(), and ft_boat_2_4().
ft_test_born()
int ft_test_born (int indice_col, int indice_line)
Vérifie si on reste bien dans la grille.
Vérifie que le nombre de colonne et ligne est bien inférieurs aux limites.
Parameters
indice_col Le nombre de colonne.
indice_line Le nombre de ligne .
Returns
Renvoie un entier 0 si tout ce passe bien, sinon 1.
Definition at line 18 of file create_grid.c.
Referenced by ft_boat_1_2(), ft_boat_1_3(), ft_boat_1_4(), ft_boat_1_4_1_3(), ft_boat_1_5(), ft_boat_1_6(), ft_boat_2_2(), and ft_boat_2_4().