My Project: navalfight.h File Reference
navalfight.h File Reference
Le header comportant les includes et prototype des fonctions.
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>
#include <unistd.h>
Functions
int ft_test_born (int indice_col, int indice_line)
Vérifie si on reste bien dans la grille.
int ft_test_boat (char **grid, int indice_col, int indice_line)
Test s'il y a un bateau.
int ft_boat_1_2 (char **grid, int indice_col, int indice_line)
Place un bateau de dimension 2.
int ft_boat_1_3 (char **grid, int indice_col, int indice_line)
Place un bateau de dimension 3.
int ft_boat_1_4 (char **grid, int indice_col, int indice_line)
Place un bateau de dimension 4.
int ft_boat_1_5 (char **grid, int indice_col, int indice_line)
Place un bateau de dimension 5.
int ft_boat_1_6 (char **grid, int indice_col, int indice_line)
Place un bateau de dimension 6.
int ft_boat_2_2 (char **grid, int indice_col, int indice_line)
Place un bateau de dimension 4.
int ft_boat_2_4 (char **grid, int indice_col, int indice_line)
Place un bateau de dimension 8.
int ft_boat_1_4_1_3 (char **grid, int indice_col, int indice_line)
Place un bateau de dimension 6.
char ** ft_fill_grid (char **grid)
Fonction qui remplie la grille.
char ** cree_tableau (void)
Fonction qui crée la grille.
int couler_droite (int x, int y, char **grid, int conteur)
Verifie s'il y a un bateau coulé coté droit.
int couler_gauche (int x, int y, char **grid, int conteur)
Verifie s'il y a un bateau coulé coté gauche .
int couler_haut (int x, int y, char **grid, int conteur)
Verifie s'il y a un bateau coulé coté haut .
int couler_bas (int x, int y, char **grid, int conteur)
Verifie s'il y a un bateau coulé coté bas .
int couler (int x, int y, char **grid)
Appel de toute les fonctions coulées .
int put_couler_droite (int x, int y, char **grid, int conteur)
Applique si coulé coté droit .
int put_couler_gauche (int x, int y, char **grid, int conteur)
Applique si coulé coté gauche .
int put_couler_haut (int x, int y, char **grid, int conteur)
Applique si coulé coté haut .
int put_couler_bas (int x, int y, char **grid, int conteur)
Applique si coulé coté bas .
int put_couler (int x, int y, char **grid)
Appel toute les fonctions put_couler .
int ft_detect_defaite (char **grid)
Test s'il reste au moin un bateau non coulé
void afficher (char **grille)
Fonction qui affiche le tableau.
char * nomjoueur (void)
Saisis les noms des joueurs.
void viderbuffer (void)
Fonction qui vide un buffer.
void findepartie (void)
Termine la partie.
void insert (char **grid, int ligne, int colonne)
Vérifie si les bateaux sont touchés.
int verifie (char **grid, int ligne, int colonne)
Vérifie les positions attaqué
int attaquer (char **grid)
Phase d'attaque.
void boucle (char **grid, char **)
Boucle principal du jeu.
int main (void)
Le main du programme.
Detailed Description
Le header comportant les includes et prototype des fonctions.
Definition in file navalfight.h.
Function Documentation
afficher()
void afficher (char ** grille)
Fonction qui affiche le tableau.
Affiche grille de la bataille navale
Parameters
char** Grille de la bataille navale
Definition at line 15 of file afficha.c.
Referenced by boucle().
attaquer()
int attaquer (char ** grid)
Phase d'attaque.
Demande d'entré la ligne et colonne a laquelle le joueur souhaite attaquer. Puis appel la fonction verifie, qui s'occupe de voir s'il a touché un bateau.
Parameters
**grid Correspond à la grille.
Returns
Renvoie un entier qui vaut 0 si le joueur à touché un bateau ou raté, sinon 1.
Definition at line 125 of file boucle.c.
References verifie(), and viderbuffer().
Referenced by boucle().
boucle()
void boucle (char ** grid1, char ** grid2)
Boucle principal du jeu.
C'est la boucle principal du jeu, qui s'occupe d'appeler les différents fonctions .
Parameters
**grid1 Grille du joueur 1.
**grid2 Grille du joueur 2.
Definition at line 178 of file boucle.c.
References afficher(), attaquer(), and nomjoueur().
Referenced by main().
couler()
int couler (int x, int y, char ** grid)
Appel de toute les fonctions coulées .
Appel toute les fonctions coulées pour vérifier s'il y a un bateau entierement coulé .
Parameters
x Premiere coordonée
y Seconde coordonée.
**grid La grille de la bataille navale.
Returns
Renvoie un entier supérieur à 0 si le bateau est coulé .
Definition at line 146 of file test_couler.c.
References couler_bas(), couler_droite(), couler_gauche(), and couler_haut().
Referenced by insert().
couler_bas()
int couler_bas (int x, int y, char ** grid, int conteur)
Verifie s'il y a un bateau coulé coté bas .
Si la position x,y est touché, verifie si sa gauche,droite,bas sont coulé aussi.
Parameters
x Premiere coordonée
y Seconde coordonée.
**grid La grille de la bataille navale.
conteur Zone dans laquel on vérifie s'il y a un bateau.
Returns
Renvoie un entier qui vaut 1 s'il y a un bateau en position x,y. Renvoie 0 si la grille est vide ou deja attaqué . Renvoie un entier supérieur à 1 si plus de 2 zone touché.
Definition at line 117 of file test_couler.c.
References couler_droite(), and couler_gauche().
Referenced by couler(), couler_droite(), and couler_gauche().
couler_droite()
int couler_droite (int x, int y, char ** grid, int conteur)
Verifie s'il y a un bateau coulé coté droit.
Si la position x,y est touché, verifie si sa droite,bas,haut sont coulé aussi.
Parameters
x Premiere coordonée
y Seconde coordonée.
**grid La grille de la bataille navale.
conteur Zone dans laquel on vérifie s'il y a un bateau.
Returns
Renvoie un entier qui vaut 1 s'il y a un bateau en position x,y. Renvoie 0 si la grille est vide ou deja attaqué . Renvoie un entier supérieur à 1 si plus de 2 zone touché.
Definition at line 22 of file test_couler.c.
References couler_bas(), and couler_haut().
Referenced by couler(), couler_bas(), and couler_haut().
couler_gauche()
int couler_gauche (int x, int y, char ** grid, int conteur)
Verifie s'il y a un bateau coulé coté gauche .
Si la position x,y est touché, verifie si sa gauche,bas,haut sont coulé aussi.
Parameters
x Premiere coordonée
y Seconde coordonée.
**grid La grille de la bataille navale.
conteur Zone dans laquel on vérifie s'il y a un bateau.
Returns
Renvoie un entier qui vaut 1 s'il y a un bateau en position x,y. Renvoie 0 si la grille est vide ou deja attaqué . Renvoie un entier supérieur à 1 si plus de 2 zone touché.
Definition at line 54 of file test_couler.c.
References couler_bas(), and couler_haut().
Referenced by couler(), couler_bas(), and couler_haut().
couler_haut()
int couler_haut (int x, int y, char ** grid, int conteur)
Verifie s'il y a un bateau coulé coté haut .
Si la position x,y est touché, verifie si sa gauche,droite,haut sont coulé aussi.
Parameters
x Premiere coordonée
y Seconde coordonée.
**grid La grille de la bataille navale.
conteur Zone dans laquel on vérifie s'il y a un bateau.
Returns
Renvoie un entier qui vaut 1 s'il y a un bateau en position x,y. Renvoie 0 si la grille est vide ou deja attaqué . Renvoie un entier supérieur à 1 si plus de 2 zone touché.
Definition at line 86 of file test_couler.c.
References couler_droite(), and couler_gauche().
Referenced by couler(), couler_droite(), and couler_gauche().
cree_tableau()
char** cree_tableau (void)
Fonction qui crée la grille.
Crée la grille, puis applique ft_fill_grid sur la grille pour la remplir .
Returns
Renvoie un char ** qui correspond à la grille.
Definition at line 773 of file create_grid.c.
References ft_fill_grid().
Referenced by main().
findepartie()
void findepartie (void)
Termine la partie.
Affiche Gagné et termine le programme . des coordonnées des points. (cf #Point)
Definition at line 51 of file boucle.c.
Referenced by insert().
ft_boat_1_2()
int ft_boat_1_2 (char ** grid, int indice_col, int indice_line)
Place un bateau de dimension 2.
Vérifie s'il y a des bateaux aux alentours des coordonées passées, si non un bateau est placé en verifiant que l'on ne sors pas de la grille.
Parameters
**grid Grille de la bataille navale .
indice_col Premiere coordonée.
indice_line Seconde coordonée.
Returns
Renvoie un entier qui vaut 0 si le bateau a été placé, sinon 0.
Definition at line 56 of file create_grid.c.
References ft_test_boat(), and ft_test_born().
Referenced by ft_fill_grid().
ft_boat_1_3()
int ft_boat_1_3 (char ** grid, int indice_col, int indice_line)
Place un bateau de dimension 3.
Vérifie s'il y a des bateaux aux alentours des coordonées passées, si non un bateau est placé en verifiant que l'on ne sors pas de la grille.
Parameters
**grid Grille de la bataille navale .
indice_col Premiere coordonée.
indice_line Seconde coordonée.
Returns
Renvoie un entier qui vaut 0 si le bateau a été placé, sinon 0.
Definition at line 108 of file create_grid.c.
References ft_test_boat(), and ft_test_born().
Referenced by ft_fill_grid().
ft_boat_1_4()
int ft_boat_1_4 (char ** grid, int indice_col, int indice_line)
Place un bateau de dimension 4.
Vérifie s'il y a des bateaux aux alentours des coordonées passées, si non un bateau est placé en verifiant que l'on ne sors pas de la grille.
Parameters
**grid Grille de la bataille navale .
indice_col Premiere coordonée.
indice_line Seconde coordonée.
Returns
Renvoie un entier qui vaut 0 si le bateau a été placé, sinon 0.
Definition at line 167 of file create_grid.c.
References ft_test_boat(), and ft_test_born().
Referenced by ft_fill_grid().
ft_boat_1_4_1_3()
int ft_boat_1_4_1_3 (char ** grid, int indice_col, int indice_line)
Place un bateau de dimension 6.
Vérifie s'il y a des bateaux aux alentours des coordonées passées, si non un bateau est placé en verifiant que l'on ne sors pas de la grille.
Parameters
**grid Grille de la bataille navale .
indice_col Premiere coordonée.
indice_line Seconde coordonée.
Returns
Renvoie un entier qui vaut 0 si le bateau a été placé, sinon 0.
Definition at line 616 of file create_grid.c.
References ft_test_boat(), and ft_test_born().
Referenced by ft_fill_grid().
ft_boat_1_5()
int ft_boat_1_5 (char ** grid, int indice_col, int indice_line)
Place un bateau de dimension 5.
Vérifie s'il y a des bateaux aux alentours des coordonées passées, si non un bateau est placé en verifiant que l'on ne sors pas de la grille.
Parameters
**grid Grille de la bataille navale .
indice_col Premiere coordonée.
indice_line Seconde coordonée.
Returns
Renvoie un entier qui vaut 0 si le bateau a été placé, sinon 0.
Definition at line 245 of file create_grid.c.
References ft_test_boat(), and ft_test_born().
Referenced by ft_fill_grid().
ft_boat_1_6()
int ft_boat_1_6 (char ** grid, int indice_col, int indice_line)
Place un bateau de dimension 6.
Vérifie s'il y a des bateaux aux alentours des coordonées passées, si non un bateau est placé en verifiant que l'on ne sors pas de la grille.
Parameters
**grid Grille de la bataille navale .
indice_col Premiere coordonée.
indice_line Seconde coordonée.
Returns
Renvoie un entier qui vaut 0 si le bateau a été placé, sinon 0.
Definition at line 336 of file create_grid.c.
References ft_test_boat(), and ft_test_born().
Referenced by ft_fill_grid().
ft_boat_2_2()
int ft_boat_2_2 (char ** grid, int indice_col, int indice_line)
Place un bateau de dimension 4.
Vérifie s'il y a des bateaux aux alentours des coordonées passées, si non un bateau est placé en verifiant que l'on ne sors pas de la grille.
Parameters
**grid Grille de la bataille navale .
indice_col Premiere coordonée.
indice_line Seconde coordonée.
Returns
Renvoie un entier qui vaut 0 si le bateau a été placé, sinon 0.
Definition at line 439 of file create_grid.c.
References ft_test_boat(), and ft_test_born().
Referenced by ft_fill_grid().
ft_boat_2_4()
int ft_boat_2_4 (char ** grid, int indice_col, int indice_line)
Place un bateau de dimension 8.
Vérifie s'il y a des bateaux aux alentours des coordonées passées, si non un bateau est placé en verifiant que l'on ne sors pas de la grille.
Parameters
**grid Grille de la bataille navale .
indice_col Premiere coordonée.
indice_line Seconde coordonée.
Returns
Renvoie un entier qui vaut 0 si le bateau a été placé, sinon 0.
Definition at line 508 of file create_grid.c.
References ft_test_boat(), and ft_test_born().
Referenced by ft_fill_grid().
ft_detect_defaite()
int ft_detect_defaite (char ** grid)
Test s'il reste au moin un bateau non coulé
Parcours la grille et vérifie s'il reste au moin un 'O' , c'est a dire au moin un bateau non coulé, sinon tout les bateaux sont coulés
Parameters
**grid La grille est passé en paramètre .
Returns
Renvoie un entier 1 si il reste au moin un bateau, 0 si tout les bateaux sont coulés.
Definition at line 16 of file defaite.c.
Referenced by insert().
ft_fill_grid()
char** ft_fill_grid (char ** grid)
Fonction qui remplie la grille.
Choisis des coordonnées aléatoires et appel les fonctions qui place bateaux avec ces coordonées .
Parameters
**grid Grille de la bataille navale .
Returns
Renvoie un char ** qui correspond à la grille remplie .
Definition at line 714 of file create_grid.c.
References ft_boat_1_2(), ft_boat_1_3(), ft_boat_1_4(), ft_boat_1_4_1_3(), ft_boat_1_5(), ft_boat_1_6(), ft_boat_2_2(), and ft_boat_2_4().
Referenced by cree_tableau().
ft_test_boat()
int ft_test_boat (char ** grid, int indice_col, int indice_line)
Test s'il y a un bateau.
Verifie s'il y a bateau aux coordonées passé
Parameters
**grid La grille de la bataille navale.
indice_col Première coordonée.
indice_line Seconde coordonée.
Returns
Renvoie un entier 1 s'il y a un bateau, sinon 0.
Definition at line 40 of file create_grid.c.
Referenced by ft_boat_1_2(), ft_boat_1_3(), ft_boat_1_4(), ft_boat_1_4_1_3(), ft_boat_1_5(), ft_boat_1_6(), ft_boat_2_2(), and ft_boat_2_4().
ft_test_born()
int ft_test_born (int indice_col, int indice_line)
Vérifie si on reste bien dans la grille.
Vérifie que le nombre de colonne et ligne est bien inférieurs aux limites.
Parameters
indice_col Le nombre de colonne.
indice_line Le nombre de ligne .
Returns
Renvoie un entier 0 si tout ce passe bien, sinon 1.
Definition at line 18 of file create_grid.c.
Referenced by ft_boat_1_2(), ft_boat_1_3(), ft_boat_1_4(), ft_boat_1_4_1_3(), ft_boat_1_5(), ft_boat_1_6(), ft_boat_2_2(), and ft_boat_2_4().
insert()
void insert (char ** grid, int ligne, int colonne)
Vérifie si les bateaux sont touchés.
Si un bateau est touché remplace le '0' par '+' et affiche Gagné sinon Raté et affiche la position par '*'. Puis appel les fonction couler et put_couler pour vérifier si le bateau est coulé. Verifie ensuite si la partie est gagné .
Parameters
**grid La grille.
ligne Le nombre de ligne de la grille .
colonne Le nombre de colonne de la grille .
Definition at line 66 of file boucle.c.
References couler(), findepartie(), ft_detect_defaite(), and put_couler().
Referenced by verifie().
main()
int main (void)
Le main du programme.
Créer les grilles et appel la boucle princpale
Returns
Renvoie 0, si tout ce passe bien.
Definition at line 15 of file main.c.
References boucle(), and cree_tableau().
nomjoueur()
char* nomjoueur (void)
Saisis les noms des joueurs.
Crée un tableau via malloc pour y saisir le nom des joueurs .
Returns
Renvoie un char * , qui contient le nom du joueur .
Definition at line 17 of file boucle.c.
Referenced by boucle().
put_couler()
int put_couler (int x, int y, char ** grid)
Appel toute les fonctions put_couler .
Toute les fonctions put_couler sont appelé pour transformer tout les '+' en 'X' pour signaler que ce bateau est coulé .
Parameters
x Premiere coordonée
y Seconde coordonée.
**grid La grille de la bataille navale.
Returns
Renvoie 0 si le bateau n'est pas entierement coulé . Renvoie un entier supérieur à 0 sinon .
Definition at line 146 of file put_couler.c.
References put_couler_bas(), put_couler_droite(), put_couler_gauche(), and put_couler_haut().
Referenced by insert().
put_couler_bas()
int put_couler_bas (int x, int y, char ** grid, int conteur)
Applique si coulé coté bas .
Si le bateau est entierement coulé transforme '+' par 'X' .
Parameters
x Premiere coordonée
y Seconde coordonée.
**grid La grille de la bataille navale.
conteur Zone dans laquel on vérifie s'il y a un bateau.
Returns
Renvoie 0 si le bateau n'est pas entierement coulé . Renvoie un entier supérieur à 0 sinon .
Definition at line 114 of file put_couler.c.
References put_couler_droite(), and put_couler_gauche().
Referenced by put_couler(), put_couler_droite(), and put_couler_gauche().
put_couler_droite()
int put_couler_droite (int x, int y, char ** grid, int conteur)
Applique si coulé coté droit .
Si le bateau est entierement coulé transforme '+' par 'X' .
Parameters
x Premiere coordonée
y Seconde coordonée.
**grid La grille de la bataille navale.
conteur Zone dans laquel on vérifie s'il y a un bateau.
Returns
Renvoie 0 si le bateau n'est pas entierement coulé . Renvoie un entier supérieur à 0 sinon .
Definition at line 21 of file put_couler.c.
References put_couler_bas(), and put_couler_haut().
Referenced by put_couler(), put_couler_bas(), and put_couler_haut().
put_couler_gauche()
int put_couler_gauche (int x, int y, char ** grid, int conteur)
Applique si coulé coté gauche .
Si le bateau est entierement coulé transforme '+' par 'X' .
Parameters
x Premiere coordonée
y Seconde coordonée.
**grid La grille de la bataille navale.
conteur Zone dans laquel on vérifie s'il y a un bateau.
Returns
Renvoie 0 si le bateau n'est pas entierement coulé . Renvoie un entier supérieur à 0 sinon .
Definition at line 51 of file put_couler.c.
References put_couler_bas(), and put_couler_haut().
Referenced by put_couler(), put_couler_bas(), and put_couler_haut().
put_couler_haut()
int put_couler_haut (int x, int y, char ** grid, int conteur)
Applique si coulé coté haut .
Si le bateau est entierement coulé transforme '+' par 'X' .
Parameters
x Premiere coordonée
y Seconde coordonée.
**grid La grille de la bataille navale.
conteur Zone dans laquel on vérifie s'il y a un bateau.
Returns
Renvoie 0 si le bateau n'est pas entierement coulé . Renvoie un entier supérieur à 0 sinon .
Definition at line 83 of file put_couler.c.
References put_couler_droite(), and put_couler_gauche().
Referenced by put_couler(), put_couler_droite(), and put_couler_gauche().
verifie()
int verifie (char ** grid, int ligne, int colonne)
Vérifie les positions attaqué
Vérifie si les positions attaqué avec la fonction insert, selon les cas 'Raté', 'Touché' ou déjà attaqué.
Parameters
**grid La grille.
ligne Le nombre de ligne de la grille .
colonne Le nombre de colonne de la grille .
Returns
Renvoie un entier, 0 si Touché un bateau ou Raté, sinon 1 .
Definition at line 99 of file boucle.c.
References insert().
Referenced by attaquer().
viderbuffer()
void viderbuffer (void)
Fonction qui vide un buffer.
Vide le buffer qui comporte la ligne et colonne joué pour les réutiliser au prochain tour de boucle.
Definition at line 36 of file boucle.c.
Referenced by attaquer().