My Project: put_couler.c File Reference
put_couler.c File Reference
Se charge d'appliquer quand un bateau est coulé.
#include "navalfight.h"
Functions
int put_couler_droite (int x, int y, char **grid, int conteur)
Applique si coulé coté droit .
int put_couler_gauche (int x, int y, char **grid, int conteur)
Applique si coulé coté gauche .
int put_couler_haut (int x, int y, char **grid, int conteur)
Applique si coulé coté haut .
int put_couler_bas (int x, int y, char **grid, int conteur)
Applique si coulé coté bas .
int put_couler (int x, int y, char **grid)
Appel toute les fonctions put_couler .
Detailed Description
Se charge d'appliquer quand un bateau est coulé.
Definition in file put_couler.c.
Function Documentation
put_couler()
int put_couler (int x, int y, char ** grid)
Appel toute les fonctions put_couler .
Toute les fonctions put_couler sont appelé pour transformer tout les '+' en 'X' pour signaler que ce bateau est coulé .
Parameters
x Premiere coordonée
y Seconde coordonée.
**grid La grille de la bataille navale.
Returns
Renvoie 0 si le bateau n'est pas entierement coulé . Renvoie un entier supérieur à 0 sinon .
Definition at line 146 of file put_couler.c.
References put_couler_bas(), put_couler_droite(), put_couler_gauche(), and put_couler_haut().
Referenced by insert().
put_couler_bas()
int put_couler_bas (int x, int y, char ** grid, int conteur)
Applique si coulé coté bas .
Si le bateau est entierement coulé transforme '+' par 'X' .
Parameters
x Premiere coordonée
y Seconde coordonée.
**grid La grille de la bataille navale.
conteur Zone dans laquel on vérifie s'il y a un bateau.
Returns
Renvoie 0 si le bateau n'est pas entierement coulé . Renvoie un entier supérieur à 0 sinon .
Definition at line 114 of file put_couler.c.
References put_couler_droite(), and put_couler_gauche().
Referenced by put_couler(), put_couler_droite(), and put_couler_gauche().
put_couler_droite()
int put_couler_droite (int x, int y, char ** grid, int conteur)
Applique si coulé coté droit .
Si le bateau est entierement coulé transforme '+' par 'X' .
Parameters
x Premiere coordonée
y Seconde coordonée.
**grid La grille de la bataille navale.
conteur Zone dans laquel on vérifie s'il y a un bateau.
Returns
Renvoie 0 si le bateau n'est pas entierement coulé . Renvoie un entier supérieur à 0 sinon .
Definition at line 21 of file put_couler.c.
References put_couler_bas(), and put_couler_haut().
Referenced by put_couler(), put_couler_bas(), and put_couler_haut().
put_couler_gauche()
int put_couler_gauche (int x, int y, char ** grid, int conteur)
Applique si coulé coté gauche .
Si le bateau est entierement coulé transforme '+' par 'X' .
Parameters
x Premiere coordonée
y Seconde coordonée.
**grid La grille de la bataille navale.
conteur Zone dans laquel on vérifie s'il y a un bateau.
Returns
Renvoie 0 si le bateau n'est pas entierement coulé . Renvoie un entier supérieur à 0 sinon .
Definition at line 51 of file put_couler.c.
References put_couler_bas(), and put_couler_haut().
Referenced by put_couler(), put_couler_bas(), and put_couler_haut().
put_couler_haut()
int put_couler_haut (int x, int y, char ** grid, int conteur)
Applique si coulé coté haut .
Si le bateau est entierement coulé transforme '+' par 'X' .
Parameters
x Premiere coordonée
y Seconde coordonée.
**grid La grille de la bataille navale.
conteur Zone dans laquel on vérifie s'il y a un bateau.
Returns
Renvoie 0 si le bateau n'est pas entierement coulé . Renvoie un entier supérieur à 0 sinon .
Definition at line 83 of file put_couler.c.
References put_couler_droite(), and put_couler_gauche().
Referenced by put_couler(), put_couler_droite(), and put_couler_gauche().