My Project: test_couler.c File Reference
test_couler.c File Reference
Verifie si les bateaux sont coulés.
#include "navalfight.h"
Functions
int couler_droite (int x, int y, char **grid, int conteur)
Verifie s'il y a un bateau coulé coté droit.
int couler_gauche (int x, int y, char **grid, int conteur)
Verifie s'il y a un bateau coulé coté gauche .
int couler_haut (int x, int y, char **grid, int conteur)
Verifie s'il y a un bateau coulé coté haut .
int couler_bas (int x, int y, char **grid, int conteur)
Verifie s'il y a un bateau coulé coté bas .
int couler (int x, int y, char **grid)
Appel de toute les fonctions coulées .
Detailed Description
Verifie si les bateaux sont coulés.
Definition in file test_couler.c.
Function Documentation
couler()
int couler (int x, int y, char ** grid)
Appel de toute les fonctions coulées .
Appel toute les fonctions coulées pour vérifier s'il y a un bateau entierement coulé .
Parameters
x Premiere coordonée
y Seconde coordonée.
**grid La grille de la bataille navale.
Returns
Renvoie un entier supérieur à 0 si le bateau est coulé .
Definition at line 146 of file test_couler.c.
References couler_bas(), couler_droite(), couler_gauche(), and couler_haut().
Referenced by insert().
couler_bas()
int couler_bas (int x, int y, char ** grid, int conteur)
Verifie s'il y a un bateau coulé coté bas .
Si la position x,y est touché, verifie si sa gauche,droite,bas sont coulé aussi.
Parameters
x Premiere coordonée
y Seconde coordonée.
**grid La grille de la bataille navale.
conteur Zone dans laquel on vérifie s'il y a un bateau.
Returns
Renvoie un entier qui vaut 1 s'il y a un bateau en position x,y. Renvoie 0 si la grille est vide ou deja attaqué . Renvoie un entier supérieur à 1 si plus de 2 zone touché.
Definition at line 117 of file test_couler.c.
References couler_droite(), and couler_gauche().
Referenced by couler(), couler_droite(), and couler_gauche().
couler_droite()
int couler_droite (int x, int y, char ** grid, int conteur)
Verifie s'il y a un bateau coulé coté droit.
Si la position x,y est touché, verifie si sa droite,bas,haut sont coulé aussi.
Parameters
x Premiere coordonée
y Seconde coordonée.
**grid La grille de la bataille navale.
conteur Zone dans laquel on vérifie s'il y a un bateau.
Returns
Renvoie un entier qui vaut 1 s'il y a un bateau en position x,y. Renvoie 0 si la grille est vide ou deja attaqué . Renvoie un entier supérieur à 1 si plus de 2 zone touché.
Definition at line 22 of file test_couler.c.
References couler_bas(), and couler_haut().
Referenced by couler(), couler_bas(), and couler_haut().
couler_gauche()
int couler_gauche (int x, int y, char ** grid, int conteur)
Verifie s'il y a un bateau coulé coté gauche .
Si la position x,y est touché, verifie si sa gauche,bas,haut sont coulé aussi.
Parameters
x Premiere coordonée
y Seconde coordonée.
**grid La grille de la bataille navale.
conteur Zone dans laquel on vérifie s'il y a un bateau.
Returns
Renvoie un entier qui vaut 1 s'il y a un bateau en position x,y. Renvoie 0 si la grille est vide ou deja attaqué . Renvoie un entier supérieur à 1 si plus de 2 zone touché.
Definition at line 54 of file test_couler.c.
References couler_bas(), and couler_haut().
Referenced by couler(), couler_bas(), and couler_haut().
couler_haut()
int couler_haut (int x, int y, char ** grid, int conteur)
Verifie s'il y a un bateau coulé coté haut .
Si la position x,y est touché, verifie si sa gauche,droite,haut sont coulé aussi.
Parameters
x Premiere coordonée
y Seconde coordonée.
**grid La grille de la bataille navale.
conteur Zone dans laquel on vérifie s'il y a un bateau.
Returns
Renvoie un entier qui vaut 1 s'il y a un bateau en position x,y. Renvoie 0 si la grille est vide ou deja attaqué . Renvoie un entier supérieur à 1 si plus de 2 zone touché.
Definition at line 86 of file test_couler.c.
References couler_droite(), and couler_gauche().
Referenced by couler(), couler_droite(), and couler_gauche().